#!/bin/sh /etc/rc.common
# Copyright (C) 2023 ImmortalWrt.org

START=75
USE_PROCD=1

WORK_DIR="/etc/oxidns"
CONF="$WORK_DIR/config.yaml"
PROG="/usr/bin/oxidns"

service_triggers() {
	procd_add_reload_trigger "oxidns"
}

start_service() {
	procd_open_instance oxidns
	procd_set_param command $PROG start
	procd_append_param command -c "$CONF"
	procd_append_param command -d "$WORK_DIR"
	procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_close_instance oxidns
}
