name: Update doggo

on:
  workflow_dispatch:

  schedule:
    - cron: "10 0 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get latest release
        id: release
        run: |
          VERSION=$(curl -fsSL \
            https://api.github.com/repos/mr-karan/doggo/releases/latest \
            | jq -r '.tag_name')

          echo "version=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Get current version
        id: current
        run: |
          VERSION=$(grep '^PKG_VERSION:=' doggo/Makefile | cut -d= -f2)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check update
        id: check
        run: |
          if [ "${{ steps.release.outputs.version }}" != "${{ steps.current.outputs.version }}" ]; then
            echo "update=true" >> "$GITHUB_OUTPUT"
          else
            echo "update=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Download release files
        if: steps.check.outputs.update == 'true'
        run: |
          VERSION=${{ steps.release.outputs.version }}
          BASE_URL="https://codeload.github.com/mr-karan/doggo/tar.gz/v${VERSION}"

          wget -q "${BASE_URL}" -O code.tar.gz

      - name: Calculate hashes
        if: steps.check.outputs.update == 'true'
        run: |
          echo "PKG_HASH=$(sha256sum code.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      - name: Update Makefile
        if: steps.check.outputs.update == 'true'
        run: |
          MAKEFILE=doggo/Makefile

          sed -i \
            "s/^PKG_VERSION:=.*/PKG_VERSION:=${{ steps.release.outputs.version }}/" \
            "$MAKEFILE"

          sed -i \
            "s/^PKG_HASH:=.*/PKG_HASH:=${PKG_HASH}/" \
            "$MAKEFILE"

      - name: Commit changes
        if: steps.check.outputs.update == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add doggo/Makefile

          git diff --cached --quiet && exit 0

          git commit -m "doggo: bump to v${{ steps.release.outputs.version }}"

          git push